baseURL = "https://www.seuh.org/seuh2022/"
languageCode = "de-de"
title = "SEUH 2022"
theme = "hugo-hero-theme"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

[params]
  google_analytics_id=""

  [params.homepage_meta_tags]
    meta_description = "SEUH is a conference series"
    meta_og_title = "SEUH 2022"
    meta_og_type = "website"
    meta_og_url = "https://seuh.org/seuh2022"
    #meta_og_image = ""
    meta_og_description = ""
    meta_twitter_card = "summary"
    meta_twitter_site = "@seuh2022"
    meta_twitter_creator = "@seuh2022"

[[menu.main]]
  identifier = "seuh"
	name = "SEUH"
	url = "/seuh/"
  weight = 1
[[menu.main]]
  parent = "seuh"
  identifier = "/seuh/sponsors"
  name = "SEUH"
  url = "/seuh/sponsors"
  weight = 1

[[menu.main]]
    name = "Programm"
    url = "/programm/"
    weight = 2

[[menu.main]]
    name = "Termine"
    url = "/termine/"
    weight = 3

[[menu.main]]
    name = "Kontakt"
    url = "/contact/"
    weight = 4

#[permalinks]
#  post = "/:year/:month/:day/:slug/"
#  pages = "/:filename/"

[security]
  enableInlineShortcodes = false
  [security.exec]
    allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$']
    osEnv = ['(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$']
  [security.funcs]
    getenv = ['^(GITHUB_REF|DRONE_COMMIT_REF|HUGO_)']
